In [33]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

import sys
sys.path.append("aav/util")
sys.path.append("lassonet")

from lassonet.interfaces import LassoNetClassifier
from config import RESIDUES, R1_TILE21_WT_SEQ

In [34]:
from lassonet import LassoNetClassifier

In [35]:
df = pd.read_csv("stat_195_project_data.csv")

In [36]:
df[df["partition"] == "stop"]

sequence partition  \
67369   *DEEEIRTTNPVATEQYGSVSTNLQRGNR      stop   
67370    *EEEIRTTNPVATEQYGSVSTNLQRGNR      stop   
88749   D*EEEIRTTNPVATEQYGSVSTNLQRGNR      stop   
88750    D*EEIRTTNPVATEQYGSVSTNLQRGNR      stop   
93223   DE*EEIRTTNPVATEQYGSVSTNLQRGNR      stop   
93224    DE*EIRTTNPVATEQYGSVSTNLQRGNR      stop   
106202  DEE*EIRTTNPVATEQYGSVSTNLQRGNR      stop   
106203   DEE*IRTTNPVATEQYGSVSTNLQRGNR      stop   
107826  DEEE*IRTTNPVATEQYGSVSTNLQRGNR      stop   
107827   DEEE*RTTNPVATEQYGSVSTNLQRGNR      stop   
108230  DEEEI*RTTNPVATEQYGSVSTNLQRGNR      stop   
108231   DEEEI*TTNPVATEQYGSVSTNLQRGNR      stop   
114505   DEEEIR*TNPVATEQYGSVSTNLQRGNR      stop   
114506  DEEEIR*TTNPVATEQYGSVSTNLQRGNR      stop   
116404   DEEEIRT*NPVATEQYGSVSTNLQRGNR      stop   
116405  DEEEIRT*TNPVATEQYGSVSTNLQRGNR      stop   
117083  DEEEIRTT*NPVATEQYGSVSTNLQRGNR      stop   
117084   DEEEIRTT*PVATEQYGSVSTNLQRGNR      stop   
117480  DEEEIRTTN*PVATEQYGSVSTNLQRGNR      stop   
117481   DEEEIRTTN*VATEQYGSVSTNLQRGNR      stop   
117970   DEEEIRTTNP*ATEQYGSVSTNLQRGNR      stop   
117971  DEEEIRTTNP*VATEQYGSVSTNLQRGNR      stop   
119063  DEEEIRTTNPV*ATEQYGSVSTNLQRGNR      stop   
119064   DEEEIRTTNPV*TEQYGSVSTNLQRGNR      stop   
119065   DEEEIRTTNPVA*EQYGSVSTNLQRGNR      stop   
119066  DEEEIRTTNPVA*TEQYGSVSTNLQRGNR      stop   
119558  DEEEIRTTNPVAT*EQYGSVSTNLQRGNR      stop   
119559   DEEEIRTTNPVAT*QYGSVSTNLQRGNR      stop   
119783  DEEEIRTTNPVATE*QYGSVSTNLQRGNR      stop   
119784   DEEEIRTTNPVATE*YGSVSTNLQRGNR      stop   
122598   DEEEIRTTNPVATEQ*GSVSTNLQRGNR      stop   
122599  DEEEIRTTNPVATEQ*YGSVSTNLQRGNR      stop   
123299  DEEEIRTTNPVATEQY*GSVSTNLQRGNR      stop   
123300   DEEEIRTTNPVATEQY*SVSTNLQRGNR      stop   
123412  DEEEIRTTNPVATEQYG*SVSTNLQRGNR      stop   
123413   DEEEIRTTNPVATEQYG*VSTNLQRGNR      stop   
130658   DEEEIRTTNPVATEQYGS*STNLQRGNR      stop   
130659  DEEEIRTTNPVATEQYGS*VSTNLQRGNR      stop   
132479  DEEEIRTTNPVATEQYGSV*STNLQRGNR      stop   
132480   DEEEIRTTNPVATEQYGSV*TNLQRGNR      stop   
135913   DEEEIRTTNPVATEQYGSVS*NLQRGNR      stop   
135914  DEEEIRTTNPVATEQYGSVS*TNLQRGNR      stop   
137547   DEEEIRTTNPVATEQYGSVST*LQRGNR      stop   
137548  DEEEIRTTNPVATEQYGSVST*NLQRGNR      stop   
138566  DEEEIRTTNPVATEQYGSVSTN*LQRGNR      stop   
138567   DEEEIRTTNPVATEQYGSVSTN*QRGNR      stop   
138871  DEEEIRTTNPVATEQYGSVSTNL*QRGNR      stop   
138872   DEEEIRTTNPVATEQYGSVSTNL*RGNR      stop   
139154   DEEEIRTTNPVATEQYGSVSTNLQ*GNR      stop   
139155  DEEEIRTTNPVATEQYGSVSTNLQ*RGNR      stop   
139385  DEEEIRTTNPVATEQYGSVSTNLQR*GNR      stop   
139386   DEEEIRTTNPVATEQYGSVSTNLQR*NR      stop   
139423  DEEEIRTTNPVATEQYGSVSTNLQRG*NR      stop   
139424   DEEEIRTTNPVATEQYGSVSTNLQRG*R      stop   
139469   DEEEIRTTNPVATEQYGSVSTNLQRGN*      stop   
139470  DEEEIRTTNPVATEQYGSVSTNLQRGN*R      stop   
139495  DEEEIRTTNPVATEQYGSVSTNLQRGNR*      stop   

                    mutation_sequence  num_mutations  num_edits  \
67369   *____________________________              1          1   
67370    *___________________________              1          1   
88749   _*___________________________              1          1   
88750    _*__________________________              1          1   
93223   __*__________________________              1          1   
93224    __*_________________________              1          1   
106202  ___*_________________________              1          1   
106203   ___*________________________              1          1   
107826  ____*________________________              1          1   
107827   ____*_______________________              1          1   
108230  _____*_______________________              1          1   
108231   _____*______________________              1          1   
114505   ______*_____________________              1          1   
114506  ______*______________________              1          1   
116404   _______*____________________              1          1  

In [37]:
sorted(df["partition"].unique())

['cnn_designed_plus_rand_train_seed',
 'cnn_designed_plus_rand_train_walked',
 'cnn_rand_doubles_plus_single_seed',
 'cnn_rand_doubles_plus_single_walked',
 'cnn_standard_seed',
 'cnn_standard_walked',
 'designed',
 'lr_designed_plus_rand_train_seed',
 'lr_designed_plus_rand_train_walked',
 'lr_rand_doubles_plus_single_seed',
 'lr_rand_doubles_plus_single_walked',
 'lr_standard_seed',
 'lr_standard_walked',
 'previous_chip_nonviable',
 'previous_chip_viable',
 'rand',
 'random_doubles',
 'rnn_designed_plus_rand_train_seed',
 'rnn_designed_plus_rand_train_walked',
 'rnn_rand_doubles_plus_singles_seed',
 'rnn_rand_doubles_plus_singles_walked',
 'rnn_standard_seed',
 'rnn_standard_walked',
 'single',
 'singles',
 'stop',
 'wild_type']

In [38]:
df_r2 = df[df["partition"] == "random_doubles"]

In [39]:
len(df_r2)

25040

In [40]:
df_r2.head(100)

sequence       partition  \
68075  AEAEIRTTNPVATEQYGSVSTNLQRGNR  random_doubles   
68760  AEEEERTTNPVATEQYGSVSTNLQRGNR  random_doubles   
69182  AEEEIGTTNPVATEQYGSVSTNLQRGNR  random_doubles   
69213  AEEEIPTTNPVATEQYGSVSTNLQRGNR  random_doubles   
69255  AEEEIRSTNPVATEQYGSVSTNLQRGNR  random_doubles   
...                             ...             ...   
89163  DAEEIRTTNPVATEQYCSVSTNLQRGNR  random_doubles   
89164  DAEEIRTTNPVATEQYGCVSTNLQRGNR  random_doubles   
89165  DAEEIRTTNPVATEQYGKVSTNLQRGNR  random_doubles   
89166  DAEEIRTTNPVATEQYGSVHTNLQRGNR  random_doubles   
89167  DAEEIRTTNPVATEQYGSVSCNLQRGNR  random_doubles   

                  mutation_sequence  num_mutations  num_edits  \
68075  A_A_________________________              2          2   
68760  A___E_______________________              2          2   
69182  A____G______________________              2          2   
69213  A____P______________________              2          2   
69255  A_____S_____________________              2          2   
...                             ...            ...        ...   
89163  _A______________C___________              2          2   
89164  _A_______________C__________              2          2   
89165  _A_______________K__________              2          2   
89166  _A_________________H________              2          2   
89167  _A__________________C_______              2          2   

       viral_selection  is_viable  
68075        -1.249723       True  
68760        -5.662130      False  
69182         0.368345       True  
69213        -6.270881      False  
69255        -0.480637       True  
...                ...        ...  
89163        -4.604482      False  
89164        -3.336564      False  
89165        -6.469121      False  
89166        -3.929963      False  
89167        -3.913640      False  

[100 rows x 7 columns]

In [41]:
from residue_encoding import ResidueIdentityEncoder
from mutation_encoding import MutationSequenceEncoder

res_encoder = ResidueIdentityEncoder(alphabet=RESIDUES)
mut_encoder = MutationSequenceEncoder(res_encoder, R1_TILE21_WT_SEQ)

In [42]:
clf_logistic = LassoNetClassifier(hidden_dims=(1,), M=30)

In [43]:
num_points = 10
X = df_r2["sequence"]
X = np.array([mut_encoder.encode(X.iloc[i]).flatten() for i in range(num_points)])
y = df_r2["is_viable"][:num_points].to_numpy().astype(int)

In [45]:
clf_logistic.fit(X, y)

TypeError: 'NoneType' object is not callable

In [20]:
clf_logistic.model.skip.weight.detach().numpy()[0]

array([ 0.01468015, -0.00220541,  0.02915093, ..., -0.02820894,
       -0.00047882, -0.01591678], dtype=float32)

In [ ]:
clf_logistic.predict(X)

array([1, 1, 1, 1, 1])

In [ ]:
RESIDUES = tuple('ACDEFGHIKLMNPQRSTVWY')
R1_TILE21_WT_SEQ = 'DEEEIRTTNPVATEQYGSVSTNLQRGNR'

In [ ]:
from residue_encoding import ResidueIdentityEncoder
from mutation_encoding import MutationSequenceEncoder

res_encoder = ResidueIdentityEncoder(alphabet=RESIDUES)
mut_encoder = MutationSequenceEncoder(res_encoder, R1_TILE21_WT_SEQ)

In [ ]:
mut_encoder.encode("cCcCBBaAA")

array([[[0., 0., 0.],
        [0., 0., 1.]],

       [[0., 0., 1.],
        [0., 0., 1.]],

       [[0., 0., 1.],
        [0., 0., 0.]],

       [[0., 1., 0.],
        [0., 0., 0.]],

       [[0., 1., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [0., 0., 0.]],

       [[1., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
clf = LassoNetClassifier(hidden_dims=(50, 50))

In [ ]:
df_r2 = df[df["partition"] == "random_doubles"]

In [ ]:
X = df_r2["sequence"]
X = np.array([mut_encoder.encode(X.iloc[i]).flatten() for i in range(5,10)])
y = df_r2["is_viable"][5:10].to_numpy().astype(int)

In [ ]:
y[-1] = 2

In [ ]:
y

array([0, 1, 1, 1, 2])

In [ ]:
clf.fit(X, y)

IndexError: Target 2 is out of bounds.

In [ ]:
clf.predict(X)

array([1, 1, 1, 1, 1])

In [ ]:
clf.model.skip.weight.shape

torch.Size([2, 1160])